# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Nombre_producto', models.CharField(max_length=35)),
                ('Precio_compra', models.CharField(max_length=35)),
                ('Precio_venta', models.CharField(max_length=35)),
                ('Existencia_minima', models.CharField(max_length=35)),
                ('Existencia_actual', models.EmailField(max_length=35)),
                ('Estado', models.CharField(max_length=35)),
            ],
        ),
    ]
