# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre_producto',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, unique=True),
        ),
    ]
