# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20180226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Existencia_actual',
            field=models.CharField(max_length=35),
        ),
    ]
