# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20180226_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Mult1',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Mult2',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
